// <auto-generated>
//   Generated from decompiled Slay the Spire 2 v0.109.0 by scratchpad/gen_ancientdata.py.
//   The relic option pools each Ancient draws from, in DECLARATION ORDER — the draws
//   index into these lists, so reordering them changes every prediction.
//   The draw algorithms themselves are hand-written in AncientOffers.cs.
// </auto-generated>

namespace Sts2.SeedFinder.Core.Ancients;

/// <summary>Gate on a Darv relic set. Darv is shared, so which act he lands in matters.</summary>
public enum DarvGate { Always, DeckNotCleared, Act2Only, Act2OrLater }

public static class AncientData
{
    // ---- Nonupeipe ---------------------------------------------------
    public static readonly string[] NonupeipeBeautifulBraceletEventOption = { "BeautifulBracelet" };
    public static readonly string[] NonupeipeOptionPool = { "BlessedAntler", "BrilliantScarf", "DelicateFrond", "DiamondDiadem", "FurCoat", "Glitter", "JewelryBox", "LoomingFruit", "SignetRing" };

    // ---- Orobas ------------------------------------------------------
    public static readonly string[] OrobasPrismaticGemOption = { "PrismaticGem" };
    public static readonly string[] OrobasOptionPool1 = { "ElectricShrymp", "GlassEye" };
    public static readonly string[] OrobasOptionPool2 = { "AlchemicalCoffer", "Driftwood", "RadiantPearl", "SandCastle" };

    // ---- Pael --------------------------------------------------------
    public static readonly string[] PaelPaelsClawOption = { "PaelsClaw" };
    public static readonly string[] PaelPaelsToothOption = { "PaelsTooth" };
    public static readonly string[] PaelPaelsGrowthOption = { "PaelsGrowth" };
    public static readonly string[] PaelPaelsLegionOption = { "PaelsLegion" };
    public static readonly string[] PaelOptionPool1 = { "PaelsFlesh", "PaelsHorn", "PaelsTears" };
    public static readonly string[] PaelOptionPool2 = { "PaelsWing" };
    public static readonly string[] PaelOptionPool3 = { "PaelsEye", "PaelsBlood" };

    // ---- Tanx --------------------------------------------------------
    public static readonly string[] TanxTriBoomerangOption = { "TriBoomerang" };
    public static readonly string[] TanxBaseOptionPool = { "Claws", "Crossbow", "IronClub", "MeatCleaver", "Sai", "SpikedGauntlets", "TanxsWhistle", "ThrowingAxe", "WarHammer" };

    // ---- Tezcatara ---------------------------------------------------
    public static readonly string[] TezcataraNutritiousSoupOption = { "NutritiousSoup" };
    public static readonly string[] TezcataraOptionPool1 = { "VeryHotCocoa", "YummyCookie" };
    public static readonly string[] TezcataraOptionPool2 = { "BiiigHug", "Storybook", "ToastyMittens" };
    public static readonly string[] TezcataraOptionPool3 = { "GoldenCompass", "PumpkinCandle", "ToyBox", "SealOfGold" };

    // ---- Vakuu -------------------------------------------------------
    public static readonly string[] VakuuPool1 = { "BloodSoakedRose", "WhisperingEarring", "Fiddle" };
    public static readonly string[] VakuuPool2 = { "PreservedFog", "SereTalon", "DistinguishedCape" };
    public static readonly string[] VakuuPool3 = { "ChoicesParadox", "MusicBox", "LordsParasol", "JeweledMask" };

    // ---- Darv --------------------------------------------------------
    /// <summary>Each set is drawn from independently, so a one-relic set still costs a draw.</summary>
    public static readonly (DarvGate Gate, string[] Relics)[] DarvRelicSets =
    {
        (DarvGate.Always, new[] { "Astrolabe" }),
        (DarvGate.Always, new[] { "BlackStar" }),
        (DarvGate.Always, new[] { "CallingBell" }),
        (DarvGate.Always, new[] { "EmptyCage" }),
        (DarvGate.DeckNotCleared, new[] { "PandorasBox" }),
        (DarvGate.Always, new[] { "RunicPyramid" }),
        (DarvGate.Always, new[] { "SneckoEye" }),
        (DarvGate.Act2Only, new[] { "Ectoplasm" }),
        (DarvGate.Act2Only, new[] { "Sozu" }),
        (DarvGate.Act2OrLater, new[] { "PhilosophersStone" }),
        (DarvGate.Act2OrLater, new[] { "VelvetChoker" }),
    };
    public const string DarvBonusRelic = "DustyTome";
}
