namespace Sts2.SeedFinder.Cli.Tools;

/// <summary>
/// One game method we reimplement, and the file that reimplements it.
/// </summary>
/// <param name="GameType">Full type name in sts2.dll.</param>
/// <param name="Method">
/// Method name. Overloads are snapshotted together, because the question is only ever "did any
/// of this change", never "which overload".
/// </param>
/// <param name="OurFile">Repo-relative path of the file that mirrors it.</param>
/// <param name="Decides">What breaks if this changes and we do not follow. Shown to the fixer.</param>
public sealed record Mirror(string GameType, string Method, string OurFile, string Decides);

/// <summary>
/// The map from the game's code to ours.
///
/// This exists because of a hard split. Data tables can be regenerated by asking the game
/// (see <see cref="GameModels"/>), but the ORDER things are drawn in is behaviour we re-expressed
/// in our own code, and no tool can re-derive that — automating it would mean compiling the
/// game's IL into our port. What a tool CAN do is notice the game's version changed and put the
/// two side by side, which turns "read 3,494 decompiled files" into "read this method".
///
/// Keeping this list complete is a maintenance duty rather than a feature: a mirrored method
/// missing from here is a change nobody will be told about. When you port a new piece of game
/// behaviour, add it here in the same commit.
/// </summary>
public static class MirrorMap
{
    public static readonly Mirror[] All =
    [
        // ---- primitives. A change here breaks everything, loudly and immediately. ----
        new("MegaCrit.Sts2.Core.Random.MegaRandom", "NextULong",
            "src/Sts2.SeedFinder.Core/MegaRandom.cs",
            "the xoshiro256** core. Every prediction in the tool."),
        new("MegaCrit.Sts2.Core.Random.MegaRandom", "NextInt",
            "src/Sts2.SeedFinder.Core/MegaRandom.cs",
            "integer draws, which is nearly every draw."),
        new("MegaCrit.Sts2.Core.Random.MegaRandom", "NextDouble",
            "src/Sts2.SeedFinder.Core/MegaRandom.cs",
            "float draws: rarity rolls, coin flips."),
        new("MegaCrit.Sts2.Core.Random.Rng", "NextInt",
            "src/Sts2.SeedFinder.Core/Rng.cs",
            "the counter-tracking wrapper every stream uses."),
        new("MegaCrit.Sts2.Core.Random.Rng", "NextItem",
            "src/Sts2.SeedFinder.Core/Rng.cs",
            "picking from a list: bosses, Ancients, cards."),
        new("MegaCrit.Sts2.Core.Helpers.StringHelper", "GetDeterministicHashCode",
            "src/Sts2.SeedFinder.Core/GameHash.cs",
            "seed string to run seed. Everything, if it changes."),
        new("MegaCrit.Sts2.Core.Helpers.StringHelper", "Slugify",
            "src/Sts2.SeedFinder.Core/GameHash.cs",
            "model ids and RNG stream names, so all named streams."),
        new("MegaCrit.Sts2.Core.Extensions.ListExtensions", "UnstableShuffle",
            "src/Sts2.SeedFinder.Core/Acts/RunGenerator.cs",
            "every shuffle: relic bags, events, Ancient pools."),

        // ---- run generation ----
        new("MegaCrit.Sts2.Core.Runs.RunManager", "GenerateRooms",
            "src/Sts2.SeedFinder.Core/Acts/RunGenerator.cs",
            "the top-level draw order, and the A10 second boss."),
        new("MegaCrit.Sts2.Core.Runs.RunManager", "InitializeNewRun",
            "src/Sts2.SeedFinder.Core/Acts/RunGenerator.cs",
            "relic bag population, which sets where every later draw lands."),
        new("MegaCrit.Sts2.Core.Models.ActModel", "GenerateRooms",
            "src/Sts2.SeedFinder.Core/Acts/RunGenerator.cs",
            "per-act order: events, encounters, boss, Ancient."),
        new("MegaCrit.Sts2.Core.Models.ActModel", "AddWithoutRepeatingTags",
            "src/Sts2.SeedFinder.Core/Acts/RunGenerator.cs",
            "encounter draw counts, via the tag retry loop."),
        new("MegaCrit.Sts2.Core.Models.ActModel", "GetRandomList",
            "src/Sts2.SeedFinder.Core/Acts/RunGenerator.cs",
            "which acts a run uses, and the singleplayer force-pick."),
        new("MegaCrit.Sts2.Core.Runs.RelicGrabBag", "Populate",
            "src/Sts2.SeedFinder.Core/Acts/RunGenerator.cs",
            "how bags are bucketed and shuffled. Shop relics, and all draw accounting."),
        new("MegaCrit.Sts2.Core.Helpers.GrabBag`1", "GrabIndex",
            "src/Sts2.SeedFinder.Core/Acts/GrabBag.cs",
            "weighted picks and the predicate retry, used for every encounter."),
        new("MegaCrit.Sts2.Core.Helpers.GrabBag`1", "GrabAndRemove",
            "src/Sts2.SeedFinder.Core/Acts/GrabBag.cs",
            "drawing without replacement, which is how encounters are dealt."),

        // ---- per-player offers ----
        new("MegaCrit.Sts2.Core.Models.Events.Neow", "GenerateInitialOptions",
            "src/Sts2.SeedFinder.Core/Neow/NeowGenerator.cs",
            "Neow's three options and the order they are drawn."),
        new("MegaCrit.Sts2.Core.Entities.Players.Player", "PlayerRng",
            "src/Sts2.SeedFinder.Core/Rng.cs",
            "the per-player seed derivation. The whole co-op premise."),
        new("MegaCrit.Sts2.Core.Rewards.RewardsSet", "GenerateRewardsFor",
            "src/Sts2.SeedFinder.Core/Cards/CardRewardGenerator.cs",
            "the first fight's card reward and its potion roll."),
        new("MegaCrit.Sts2.Core.Factories.CardFactory", "CreateForReward",
            "src/Sts2.SeedFinder.Core/Cards/CardRewardGenerator.cs",
            "rarity, pick and upgrade draws per offered card."),

        // ---- shops ----
        new("MegaCrit.Sts2.Core.Entities.Merchant.MerchantInventory", "PopulateRelicEntries",
            "src/Sts2.SeedFinder.Core/Acts/RunGenerator.cs",
            "that the third slot is hardcoded to Shop rarity. The whole shop feature."),
        new("MegaCrit.Sts2.Core.Factories.RelicFactory", "PullNextRelicFromBack",
            "src/Sts2.SeedFinder.Core/Acts/RunGenerator.cs",
            "that filling a shop slot draws no RNG."),
        new("MegaCrit.Sts2.Core.Factories.RelicFactory", "RollRarity",
            "src/Sts2.SeedFinder.Core/Acts/RunGenerator.cs",
            "that nothing but a shop ever draws Shop rarity."),
    ];

    /// <summary>Everything mirroring one of our files, for reporting a failure by file.</summary>
    public static IEnumerable<Mirror> For(string ourFile) =>
        All.Where(m => m.OurFile.Equals(ourFile, StringComparison.OrdinalIgnoreCase));

    /// <summary>Matches "Neow.GenerateInitialOptions" or a full type name, case-insensitively.</summary>
    public static IEnumerable<Mirror> Find(string query)
    {
        var q = query.Trim();
        return All.Where(m =>
            $"{m.GameType}.{m.Method}".Contains(q, StringComparison.OrdinalIgnoreCase)
            || $"{Short(m.GameType)}.{m.Method}".Equals(q, StringComparison.OrdinalIgnoreCase)
            || m.Method.Equals(q, StringComparison.OrdinalIgnoreCase));
    }

    public static string Short(string fullTypeName)
    {
        var name = fullTypeName[(fullTypeName.LastIndexOf('.') + 1)..];
        int tick = name.IndexOf('`');
        return tick < 0 ? name : name[..tick];
    }
}
