// <auto-generated>
//   Per-act generation tables: encounter pools, event pools, room counts, Ancients.
//   Read from Slay the Spire v0.109.1 by `sts2seed --refresh`, which asks the
//   game's own model database rather than parsing its source. Do not hand-edit:
//   order is load-bearing, and the next refresh will overwrite you.
//
//   COUNT Overgrowth = 22
//   COUNT Underdocks = 20
//   COUNT Hive = 20
//   COUNT Glory = 18
//   COUNT SharedEvents = 18
//   COUNT EncounterTags = 15
// </auto-generated>

#nullable enable

namespace Sts2.SeedFinder.Core.Acts;

public enum RoomType { Monster, Elite, Boss, Event }

public enum EncounterTag
{
    Burrower,
    Chomper,
    Crawler,
    Exoskeletons,
    Jaxfruit,
    Knights,
    Mushroom,
    Nibbit,
    Scrolls,
    Seapunk,
    Shrinker,
    Slimes,
    Slugs,
    Thieves,
    Workers,
}

public sealed record Encounter(string Name, RoomType RoomType, bool IsWeak, EncounterTag[] Tags)
{
    public bool SharesTagsWith(Encounter? other) => other is not null && Tags.Intersect(other.Tags).Any();
    public override string ToString() => Name;
}

public sealed record ActDefinition(
    string Name, int Index, int BaseNumberOfRooms, int NumberOfWeakEncounters,
    Encounter[] Encounters, string[] Events, string[] Ancients,
    IReadOnlyDictionary<string, string> AncientEpochGates)
{
    public IEnumerable<Encounter> Weak => Encounters.Where(e => e.RoomType == RoomType.Monster && e.IsWeak);
    public IEnumerable<Encounter> Regular => Encounters.Where(e => e.RoomType == RoomType.Monster && !e.IsWeak);
    public IEnumerable<Encounter> Elites => Encounters.Where(e => e.RoomType == RoomType.Elite);
    public IEnumerable<Encounter> Bosses => Encounters.Where(e => e.RoomType == RoomType.Boss);
    public int GetNumberOfRooms(bool isMultiplayer) => BaseNumberOfRooms - (isMultiplayer ? 1 : 0);
    public int GetNumberOfFloors(bool isMultiplayer) => GetNumberOfRooms(isMultiplayer) + 2;
    public override string ToString() => Name;
}

public static class ActData
{
    /// <summary>ModelDb.AllSharedEvents — appended to each act's own events before shuffling.</summary>
    public static readonly string[] SharedEvents = { "BrainLeech", "CrystalSphere", "DollRoom", "FakeMerchant", "PotionCourier", "RanwidTheElder", "RelicTrader", "RoomFullOfCheese", "SelfHelpBook", "SlipperyBridge", "StoneOfAllTime", "Symbiote", "TeaMaster", "TheFutureOfPotions", "TheLegendsWereTrue", "ThisOrThat", "WarHistorianRepy", "WelcomeToWongos" };

    /// <summary>Events removed unless their epoch is revealed.</summary>
    public static readonly IReadOnlyDictionary<string, string> EventEpochGates =
        new Dictionary<string, string> { ["TrashHeap"] = "Event1Epoch", ["Reflections"] = "Event2Epoch", ["ColorfulPhilosophers"] = "Event3Epoch" };

    /// <summary>Shared Ancients, distributed across acts 2+ before per-act generation.</summary>
    public static readonly string[] SharedAncients = { "Darv" };
    public const string SharedAncientEpoch = "DarvEpoch";

    public static readonly ActDefinition Overgrowth = new(
        "Overgrowth", 0, 15, 3,
        Encounters: new Encounter[]
        {
            new("BygoneEffigyElite", RoomType.Elite, false, Array.Empty<EncounterTag>()),
            new("ByrdonisElite", RoomType.Elite, false, Array.Empty<EncounterTag>()),
            new("CeremonialBeastBoss", RoomType.Boss, false, Array.Empty<EncounterTag>()),
            new("CubexConstructNormal", RoomType.Monster, false, Array.Empty<EncounterTag>()),
            new("FlyconidNormal", RoomType.Monster, false, new[] { EncounterTag.Mushroom, EncounterTag.Slimes }),
            new("FogmogNormal", RoomType.Monster, false, Array.Empty<EncounterTag>()),
            new("FuzzyWurmCrawlerWeak", RoomType.Monster, true, new[] { EncounterTag.Crawler }),
            new("InkletsNormal", RoomType.Monster, false, Array.Empty<EncounterTag>()),
            new("MawlerNormal", RoomType.Monster, false, Array.Empty<EncounterTag>()),
            new("NibbitsNormal", RoomType.Monster, false, Array.Empty<EncounterTag>()),
            new("NibbitsWeak", RoomType.Monster, true, new[] { EncounterTag.Nibbit }),
            new("OvergrowthCrawlers", RoomType.Monster, false, new[] { EncounterTag.Shrinker, EncounterTag.Crawler }),
            new("PhrogParasiteElite", RoomType.Elite, false, Array.Empty<EncounterTag>()),
            new("RubyRaidersNormal", RoomType.Monster, false, Array.Empty<EncounterTag>()),
            new("ShrinkerBeetleWeak", RoomType.Monster, true, new[] { EncounterTag.Shrinker }),
            new("SlimesNormal", RoomType.Monster, false, new[] { EncounterTag.Slimes }),
            new("SlimesWeak", RoomType.Monster, true, new[] { EncounterTag.Slimes }),
            new("SlitheringStranglerNormal", RoomType.Monster, false, new[] { EncounterTag.Jaxfruit, EncounterTag.Slimes }),
            new("SnappingJaxfruitNormal", RoomType.Monster, false, new[] { EncounterTag.Mushroom, EncounterTag.Jaxfruit }),
            new("TheKinBoss", RoomType.Boss, false, Array.Empty<EncounterTag>()),
            new("VantomBoss", RoomType.Boss, false, Array.Empty<EncounterTag>()),
            new("VineShamblerNormal", RoomType.Monster, false, Array.Empty<EncounterTag>()),
        },
        Events: new[] { "AromaOfChaos", "ByrdonisNest", "DenseVegetation", "JungleMazeAdventure", "LuminousChoir", "MorphicGrove", "SapphireSeed", "SunkenStatue", "TabletOfTruth", "UnrestSite", "Wellspring", "WhisperingHollow", "WoodCarvings" },
        Ancients: new[] { "Neow" },
        AncientEpochGates: new Dictionary<string, string> { ["Neow"] = "NeowEpoch" });

    public static readonly ActDefinition Underdocks = new(
        "Underdocks", 0, 15, 3,
        Encounters: new Encounter[]
        {
            new("CorpseSlugsNormal", RoomType.Monster, false, new[] { EncounterTag.Slugs }),
            new("CorpseSlugsWeak", RoomType.Monster, true, new[] { EncounterTag.Slugs }),
            new("CultistsNormal", RoomType.Monster, false, Array.Empty<EncounterTag>()),
            new("FossilStalkerNormal", RoomType.Monster, false, Array.Empty<EncounterTag>()),
            new("GremlinMercNormal", RoomType.Monster, false, Array.Empty<EncounterTag>()),
            new("HauntedShipNormal", RoomType.Monster, false, Array.Empty<EncounterTag>()),
            new("LagavulinMatriarchBoss", RoomType.Boss, false, Array.Empty<EncounterTag>()),
            new("LivingFogNormal", RoomType.Monster, false, Array.Empty<EncounterTag>()),
            new("PhantasmalGardenersElite", RoomType.Elite, false, Array.Empty<EncounterTag>()),
            new("PunchConstructNormal", RoomType.Monster, false, Array.Empty<EncounterTag>()),
            new("SeapunkNormal", RoomType.Monster, false, new[] { EncounterTag.Seapunk }),
            new("SeapunkWeak", RoomType.Monster, true, new[] { EncounterTag.Seapunk }),
            new("SewerClamNormal", RoomType.Monster, false, Array.Empty<EncounterTag>()),
            new("SkulkingColonyElite", RoomType.Elite, false, Array.Empty<EncounterTag>()),
            new("SludgeSpinnerWeak", RoomType.Monster, true, Array.Empty<EncounterTag>()),
            new("SoulFyshBoss", RoomType.Boss, false, Array.Empty<EncounterTag>()),
            new("TerrorEelElite", RoomType.Elite, false, Array.Empty<EncounterTag>()),
            new("ToadpolesWeak", RoomType.Monster, true, Array.Empty<EncounterTag>()),
            new("TwoTailedRatsNormal", RoomType.Monster, false, Array.Empty<EncounterTag>()),
            new("WaterfallGiantBoss", RoomType.Boss, false, Array.Empty<EncounterTag>()),
        },
        Events: new[] { "AbyssalBaths", "DrowningBeacon", "EndlessConveyor", "PunchOff", "SpiralingWhirlpool", "SunkenStatue", "SunkenTreasury", "DoorsOfLightAndDark", "TrashHeap", "WaterloggedScriptorium" },
        Ancients: new[] { "Neow" },
        AncientEpochGates: new Dictionary<string, string> { ["Neow"] = "NeowEpoch" });

    public static readonly ActDefinition Hive = new(
        "Hive", 1, 14, 2,
        Encounters: new Encounter[]
        {
            new("BowlbugsNormal", RoomType.Monster, false, new[] { EncounterTag.Workers }),
            new("BowlbugsWeak", RoomType.Monster, true, new[] { EncounterTag.Workers }),
            new("ChompersNormal", RoomType.Monster, false, new[] { EncounterTag.Chomper }),
            new("DecimillipedeElite", RoomType.Elite, false, Array.Empty<EncounterTag>()),
            new("EntomancerElite", RoomType.Elite, false, Array.Empty<EncounterTag>()),
            new("ExoskeletonsNormal", RoomType.Monster, false, new[] { EncounterTag.Exoskeletons }),
            new("ExoskeletonsWeak", RoomType.Monster, true, new[] { EncounterTag.Exoskeletons }),
            new("HunterKillerNormal", RoomType.Monster, false, Array.Empty<EncounterTag>()),
            new("KaiserCrabBoss", RoomType.Boss, false, Array.Empty<EncounterTag>()),
            new("InfestedPrismsElite", RoomType.Elite, false, Array.Empty<EncounterTag>()),
            new("KnowledgeDemonBoss", RoomType.Boss, false, Array.Empty<EncounterTag>()),
            new("LouseProgenitorNormal", RoomType.Monster, false, Array.Empty<EncounterTag>()),
            new("MytesNormal", RoomType.Monster, false, Array.Empty<EncounterTag>()),
            new("OvicopterNormal", RoomType.Monster, false, Array.Empty<EncounterTag>()),
            new("SlumberingBeetleNormal", RoomType.Monster, false, new[] { EncounterTag.Workers }),
            new("SpinyToadNormal", RoomType.Monster, false, Array.Empty<EncounterTag>()),
            new("TheInsatiableBoss", RoomType.Boss, false, Array.Empty<EncounterTag>()),
            new("TheObscuraNormal", RoomType.Monster, false, Array.Empty<EncounterTag>()),
            new("ThievingHopperWeak", RoomType.Monster, true, new[] { EncounterTag.Thieves }),
            new("TunnelerWeak", RoomType.Monster, true, new[] { EncounterTag.Burrower }),
        },
        Events: new[] { "Amalgamator", "Bugslayer", "ColorfulPhilosophers", "ColossalFlower", "FieldOfManSizedHoles", "InfestedAutomaton", "LostWisp", "SpiritGrafter", "TheLanternKey", "ZenWeaver" },
        Ancients: new[] { "Orobas", "Pael", "Tezcatara" },
        AncientEpochGates: new Dictionary<string, string> { ["Orobas"] = "OrobasEpoch" });

    public static readonly ActDefinition Glory = new(
        "Glory", 2, 13, 2,
        Encounters: new Encounter[]
        {
            new("AxebotsNormal", RoomType.Monster, false, Array.Empty<EncounterTag>()),
            new("ConstructMenagerieNormal", RoomType.Monster, false, Array.Empty<EncounterTag>()),
            new("DevotedSculptorWeak", RoomType.Monster, true, Array.Empty<EncounterTag>()),
            new("AeonglassBoss", RoomType.Boss, false, Array.Empty<EncounterTag>()),
            new("FabricatorNormal", RoomType.Monster, false, Array.Empty<EncounterTag>()),
            new("FrogKnightNormal", RoomType.Monster, false, Array.Empty<EncounterTag>()),
            new("GlobeHeadNormal", RoomType.Monster, false, Array.Empty<EncounterTag>()),
            new("KnightsElite", RoomType.Elite, false, new[] { EncounterTag.Knights }),
            new("MechaKnightElite", RoomType.Elite, false, Array.Empty<EncounterTag>()),
            new("OwlMagistrateNormal", RoomType.Monster, false, Array.Empty<EncounterTag>()),
            new("QueenBoss", RoomType.Boss, false, Array.Empty<EncounterTag>()),
            new("ScrollsOfBitingNormal", RoomType.Monster, false, new[] { EncounterTag.Scrolls }),
            new("ScrollsOfBitingWeak", RoomType.Monster, true, new[] { EncounterTag.Scrolls }),
            new("SlimedBerserkerNormal", RoomType.Monster, false, Array.Empty<EncounterTag>()),
            new("SoulNexusElite", RoomType.Elite, false, Array.Empty<EncounterTag>()),
            new("TestSubjectBoss", RoomType.Boss, false, Array.Empty<EncounterTag>()),
            new("TheLostAndForgottenNormal", RoomType.Monster, false, Array.Empty<EncounterTag>()),
            new("TurretOperatorWeak", RoomType.Monster, true, Array.Empty<EncounterTag>()),
        },
        Events: new[] { "BattlewornDummy", "GraveOfTheForgotten", "HungryForMushrooms", "Reflections", "RoundTeaParty", "Trial", "TinkerTime" },
        Ancients: new[] { "Nonupeipe", "Tanx", "Vakuu" },
        AncientEpochGates: new Dictionary<string, string> {  });

    public static readonly ActDefinition[][] ByIndex =
    {
        new[] { Overgrowth, Underdocks },
        new[] { Hive },
        new[] { Glory },
    };

    public static readonly ActDefinition[] All = { Overgrowth, Underdocks, Hive, Glory };
}
