// <auto-generated>
//   Per-act generation tables: encounter pools, event pools, room counts, Ancients.
//   Read from Slay the Spire v0.110.1 by `sts2seed --refresh`, which asks the
//   game's own model database rather than parsing its source. Do not hand-edit:
//   order is load-bearing, and the next refresh will overwrite you.
//
//   COUNT Overgrowth = 22
//   COUNT Underdocks = 20
//   COUNT Hive = 20
//   COUNT Glory = 18
//   COUNT SharedEvents = 18
//   COUNT EncounterTags = 15
// </auto-generated>

#nullable enable

namespace Sts2.SeedFinder.Core.Acts;

public enum RoomType { Monster, Elite, Boss, Event }

public enum EncounterTag
{
    Burrower,
    Chomper,
    Crawler,
    Exoskeletons,
    Jaxfruit,
    Knights,
    Mushroom,
    Nibbit,
    Scrolls,
    Seapunk,
    Shrinker,
    Slimes,
    Slugs,
    Thieves,
    Workers,
}

public sealed record Encounter(string Name, RoomType RoomType, bool IsWeak, EncounterTag[] Tags)
{
    /// <summary>
    /// <see cref="Tags"/> as a bit per tag. There are 15 of them, so one ulong holds any set.
    ///
    /// Computed once per encounter, lazily, because encounters are static data. The race between
    /// threads is benign: both compute the same value and the write is atomic. Zero is not a
    /// valid "computed" state (an encounter with no tags would produce it), hence the separate
    /// flag rather than treating 0 as "not yet done".
    /// </summary>
    private ulong _tagMask;
    private bool _maskReady;

    private ulong TagMask
    {
        get
        {
            if (_maskReady) return _tagMask;
            ulong m = 0;
            foreach (var t in Tags) m |= 1UL << (int)t;
            _tagMask = m;
            _maskReady = true;
            return m;
        }
    }

    /// <summary>
    /// Whether these two encounters have any tag in common, which is what the game's
    /// repeat-avoidance predicate asks.
    ///
    /// This was <c>Tags.Intersect(other.Tags).Any()</c>. Intersect builds a HashSet internally
    /// on every call, and the encounter draw calls this for every entry still in the bag on every
    /// draw, roughly 700 times per act. Same question, one AND, nothing allocated.
    /// </summary>
    public bool SharesTagsWith(Encounter? other) =>
        other is not null && (TagMask & other.TagMask) != 0;

    public override string ToString() => Name;
}

public sealed record ActDefinition(
    string Name, int Index, int BaseNumberOfRooms, int NumberOfWeakEncounters,
    Encounter[] Encounters, string[] Events, string[] Ancients,
    IReadOnlyDictionary<string, string> AncientEpochGates)
{
    // Computed once per act rather than per access. These were IEnumerable properties that re-ran
    // their Where over the whole Encounters array every time they were touched, and a search
    // touches them several times per act per seed: three DrawEncounters pools, the boss list, and
    // once more for every boss criterion. The acts are static data, so the answer never changes.
    //
    // The lazy fields race harmlessly under Parallel.For: two threads can both compute, both get
    // an identical array, and a reference assignment is atomic, so a reader sees either null or a
    // complete array. Filtering with Where preserves order, so the draw order is untouched.
    private Encounter[]? _weak, _regular, _elites, _bosses;

    public IReadOnlyList<Encounter> Weak =>
        _weak ??= Encounters.Where(e => e.RoomType == RoomType.Monster && e.IsWeak).ToArray();
    public IReadOnlyList<Encounter> Regular =>
        _regular ??= Encounters.Where(e => e.RoomType == RoomType.Monster && !e.IsWeak).ToArray();
    public IReadOnlyList<Encounter> Elites =>
        _elites ??= Encounters.Where(e => e.RoomType == RoomType.Elite).ToArray();
    public IReadOnlyList<Encounter> Bosses =>
        _bosses ??= Encounters.Where(e => e.RoomType == RoomType.Boss).ToArray();

    /// <summary>
    /// A cached answer together with the unlock state it was computed for, as ONE object.
    ///
    /// The pairing has to be atomic. Two fields would let a thread publish a new array before its
    /// matching unlock state, and a reader could then take an array computed for someone else's
    /// unlocks as its own. A single reference assignment cannot be seen half-done.
    /// </summary>
    private sealed record Filtered(UnlockState Unlocks, string[] Values);

    private Filtered? _events;
    private Filtered? _ancients;

    /// <summary>
    /// This act's events plus the shared ones, minus anything an unrevealed epoch gates, in pool
    /// order and ready to be copied and shuffled.
    ///
    /// Depends only on the act and the unlock state, so it is the same for every seed in a search.
    /// Recomputing it per act per seed was a Concat, a Where and a ToList over roughly forty
    /// entries, which is 24% of act generation.
    /// </summary>
    public string[] EventsFor(UnlockState unlocks)
    {
        var cached = _events;
        if (cached is not null && ReferenceEquals(cached.Unlocks, unlocks)) return cached.Values;

        var values = Events.Concat(ActData.SharedEvents)
            .Where(e => !ActData.EventEpochGates.TryGetValue(e, out var epoch) || unlocks.IsEpochRevealed(epoch))
            .ToArray();
        _events = new Filtered(unlocks, values);
        return values;
    }

    /// <summary>
    /// This act's OWN Ancients after epoch gating. The shared ones are appended per run, since
    /// which of them an act receives is a per-seed draw.
    /// </summary>
    public string[] AncientsFor(UnlockState unlocks)
    {
        var cached = _ancients;
        if (cached is not null && ReferenceEquals(cached.Unlocks, unlocks)) return cached.Values;

        var values = Ancients
            .Where(a => !AncientEpochGates.TryGetValue(a, out var epoch) || unlocks.IsEpochRevealed(epoch))
            .ToArray();
        _ancients = new Filtered(unlocks, values);
        return values;
    }
    public int GetNumberOfRooms(bool isMultiplayer) => BaseNumberOfRooms - (isMultiplayer ? 1 : 0);
    public int GetNumberOfFloors(bool isMultiplayer) => GetNumberOfRooms(isMultiplayer) + 2;
    public override string ToString() => Name;
}

public static class ActData
{
    /// <summary>ModelDb.AllSharedEvents — appended to each act's own events before shuffling.</summary>
    public static readonly string[] SharedEvents = { "BrainLeech", "CrystalSphere", "DollRoom", "FakeMerchant", "PotionCourier", "RanwidTheElder", "RelicTrader", "RoomFullOfCheese", "SelfHelpBook", "SlipperyBridge", "StoneOfAllTime", "Symbiote", "TeaMaster", "TheFutureOfPotions", "TheLegendsWereTrue", "ThisOrThat", "WarHistorianRepy", "WelcomeToWongos" };

    /// <summary>Events removed unless their epoch is revealed.</summary>
    public static readonly IReadOnlyDictionary<string, string> EventEpochGates =
        new Dictionary<string, string> { ["TrashHeap"] = "Event1Epoch", ["Reflections"] = "Event2Epoch", ["ColorfulPhilosophers"] = "Event3Epoch" };

    /// <summary>Shared Ancients, distributed across acts 2+ before per-act generation.</summary>
    public static readonly string[] SharedAncients = { "Darv" };
    public const string SharedAncientEpoch = "DarvEpoch";

    public static readonly ActDefinition Overgrowth = new(
        "Overgrowth", 0, 15, 3,
        Encounters: new Encounter[]
        {
            new("BygoneEffigyElite", RoomType.Elite, false, Array.Empty<EncounterTag>()),
            new("ByrdonisElite", RoomType.Elite, false, Array.Empty<EncounterTag>()),
            new("CeremonialBeastBoss", RoomType.Boss, false, Array.Empty<EncounterTag>()),
            new("CubexConstructNormal", RoomType.Monster, false, Array.Empty<EncounterTag>()),
            new("FlyconidNormal", RoomType.Monster, false, new[] { EncounterTag.Mushroom, EncounterTag.Slimes }),
            new("FogmogNormal", RoomType.Monster, false, Array.Empty<EncounterTag>()),
            new("FuzzyWurmCrawlerWeak", RoomType.Monster, true, new[] { EncounterTag.Crawler }),
            new("InkletsNormal", RoomType.Monster, false, Array.Empty<EncounterTag>()),
            new("MawlerNormal", RoomType.Monster, false, Array.Empty<EncounterTag>()),
            new("NibbitsNormal", RoomType.Monster, false, Array.Empty<EncounterTag>()),
            new("NibbitsWeak", RoomType.Monster, true, new[] { EncounterTag.Nibbit }),
            new("OvergrowthCrawlers", RoomType.Monster, false, new[] { EncounterTag.Shrinker, EncounterTag.Crawler }),
            new("PhrogParasiteElite", RoomType.Elite, false, Array.Empty<EncounterTag>()),
            new("RubyRaidersNormal", RoomType.Monster, false, Array.Empty<EncounterTag>()),
            new("ShrinkerBeetleWeak", RoomType.Monster, true, new[] { EncounterTag.Shrinker }),
            new("SlimesNormal", RoomType.Monster, false, new[] { EncounterTag.Slimes }),
            new("SlimesWeak", RoomType.Monster, true, new[] { EncounterTag.Slimes }),
            new("SlitheringStranglerNormal", RoomType.Monster, false, new[] { EncounterTag.Jaxfruit, EncounterTag.Slimes }),
            new("SnappingJaxfruitNormal", RoomType.Monster, false, new[] { EncounterTag.Mushroom, EncounterTag.Jaxfruit }),
            new("TheKinBoss", RoomType.Boss, false, Array.Empty<EncounterTag>()),
            new("VantomBoss", RoomType.Boss, false, Array.Empty<EncounterTag>()),
            new("VineShamblerNormal", RoomType.Monster, false, Array.Empty<EncounterTag>()),
        },
        Events: new[] { "AromaOfChaos", "ByrdonisNest", "DenseVegetation", "JungleMazeAdventure", "LuminousChoir", "MorphicGrove", "SapphireSeed", "SunkenStatue", "TabletOfTruth", "UnrestSite", "Wellspring", "WhisperingHollow", "WoodCarvings" },
        Ancients: new[] { "Neow" },
        AncientEpochGates: new Dictionary<string, string> { ["Neow"] = "NeowEpoch" });

    public static readonly ActDefinition Underdocks = new(
        "Underdocks", 0, 15, 3,
        Encounters: new Encounter[]
        {
            new("CorpseSlugsNormal", RoomType.Monster, false, new[] { EncounterTag.Slugs }),
            new("CorpseSlugsWeak", RoomType.Monster, true, new[] { EncounterTag.Slugs }),
            new("CultistsNormal", RoomType.Monster, false, Array.Empty<EncounterTag>()),
            new("FossilStalkerNormal", RoomType.Monster, false, Array.Empty<EncounterTag>()),
            new("GremlinMercNormal", RoomType.Monster, false, Array.Empty<EncounterTag>()),
            new("HauntedShipNormal", RoomType.Monster, false, Array.Empty<EncounterTag>()),
            new("LagavulinMatriarchBoss", RoomType.Boss, false, Array.Empty<EncounterTag>()),
            new("LivingFogNormal", RoomType.Monster, false, Array.Empty<EncounterTag>()),
            new("PhantasmalGardenersElite", RoomType.Elite, false, Array.Empty<EncounterTag>()),
            new("PunchConstructNormal", RoomType.Monster, false, Array.Empty<EncounterTag>()),
            new("SeapunkNormal", RoomType.Monster, false, new[] { EncounterTag.Seapunk }),
            new("SeapunkWeak", RoomType.Monster, true, new[] { EncounterTag.Seapunk }),
            new("SewerClamNormal", RoomType.Monster, false, Array.Empty<EncounterTag>()),
            new("SkulkingColonyElite", RoomType.Elite, false, Array.Empty<EncounterTag>()),
            new("SludgeSpinnerWeak", RoomType.Monster, true, Array.Empty<EncounterTag>()),
            new("SoulFyshBoss", RoomType.Boss, false, Array.Empty<EncounterTag>()),
            new("TerrorEelElite", RoomType.Elite, false, Array.Empty<EncounterTag>()),
            new("ToadpolesWeak", RoomType.Monster, true, Array.Empty<EncounterTag>()),
            new("TwoTailedRatsNormal", RoomType.Monster, false, Array.Empty<EncounterTag>()),
            new("WaterfallGiantBoss", RoomType.Boss, false, Array.Empty<EncounterTag>()),
        },
        Events: new[] { "AbyssalBaths", "DrowningBeacon", "EndlessConveyor", "PunchOff", "SpiralingWhirlpool", "SunkenStatue", "SunkenTreasury", "DoorsOfLightAndDark", "TrashHeap", "WaterloggedScriptorium" },
        Ancients: new[] { "Neow" },
        AncientEpochGates: new Dictionary<string, string> { ["Neow"] = "NeowEpoch" });

    public static readonly ActDefinition Hive = new(
        "Hive", 1, 14, 2,
        Encounters: new Encounter[]
        {
            new("BowlbugsNormal", RoomType.Monster, false, new[] { EncounterTag.Workers }),
            new("BowlbugsWeak", RoomType.Monster, true, new[] { EncounterTag.Workers }),
            new("ChompersNormal", RoomType.Monster, false, new[] { EncounterTag.Chomper }),
            new("DecimillipedeElite", RoomType.Elite, false, Array.Empty<EncounterTag>()),
            new("EntomancerElite", RoomType.Elite, false, Array.Empty<EncounterTag>()),
            new("ExoskeletonsNormal", RoomType.Monster, false, new[] { EncounterTag.Exoskeletons }),
            new("ExoskeletonsWeak", RoomType.Monster, true, new[] { EncounterTag.Exoskeletons }),
            new("HunterKillerNormal", RoomType.Monster, false, Array.Empty<EncounterTag>()),
            new("KaiserCrabBoss", RoomType.Boss, false, Array.Empty<EncounterTag>()),
            new("InfestedPrismsElite", RoomType.Elite, false, Array.Empty<EncounterTag>()),
            new("KnowledgeDemonBoss", RoomType.Boss, false, Array.Empty<EncounterTag>()),
            new("LouseProgenitorNormal", RoomType.Monster, false, Array.Empty<EncounterTag>()),
            new("MytesNormal", RoomType.Monster, false, Array.Empty<EncounterTag>()),
            new("OvicopterNormal", RoomType.Monster, false, Array.Empty<EncounterTag>()),
            new("SlumberingBeetleNormal", RoomType.Monster, false, new[] { EncounterTag.Workers }),
            new("SpinyToadNormal", RoomType.Monster, false, Array.Empty<EncounterTag>()),
            new("TheInsatiableBoss", RoomType.Boss, false, Array.Empty<EncounterTag>()),
            new("TheObscuraNormal", RoomType.Monster, false, Array.Empty<EncounterTag>()),
            new("ThievingHopperWeak", RoomType.Monster, true, new[] { EncounterTag.Thieves }),
            new("TunnelerWeak", RoomType.Monster, true, new[] { EncounterTag.Burrower }),
        },
        Events: new[] { "Amalgamator", "Bugslayer", "ColorfulPhilosophers", "ColossalFlower", "FieldOfManSizedHoles", "InfestedAutomaton", "LostWisp", "SpiritGrafter", "TheLanternKey", "ZenWeaver" },
        Ancients: new[] { "Orobas", "Pael", "Tezcatara" },
        AncientEpochGates: new Dictionary<string, string> { ["Orobas"] = "OrobasEpoch" });

    public static readonly ActDefinition Glory = new(
        "Glory", 2, 13, 2,
        Encounters: new Encounter[]
        {
            new("AxebotsNormal", RoomType.Monster, false, Array.Empty<EncounterTag>()),
            new("ConstructMenagerieNormal", RoomType.Monster, false, Array.Empty<EncounterTag>()),
            new("DevotedSculptorWeak", RoomType.Monster, true, Array.Empty<EncounterTag>()),
            new("AeonglassBoss", RoomType.Boss, false, Array.Empty<EncounterTag>()),
            new("FabricatorNormal", RoomType.Monster, false, Array.Empty<EncounterTag>()),
            new("FrogKnightNormal", RoomType.Monster, false, Array.Empty<EncounterTag>()),
            new("GlobeHeadNormal", RoomType.Monster, false, Array.Empty<EncounterTag>()),
            new("KnightsElite", RoomType.Elite, false, new[] { EncounterTag.Knights }),
            new("MechaKnightElite", RoomType.Elite, false, Array.Empty<EncounterTag>()),
            new("OwlMagistrateNormal", RoomType.Monster, false, Array.Empty<EncounterTag>()),
            new("QueenBoss", RoomType.Boss, false, Array.Empty<EncounterTag>()),
            new("ScrollsOfBitingNormal", RoomType.Monster, false, new[] { EncounterTag.Scrolls }),
            new("ScrollsOfBitingWeak", RoomType.Monster, true, new[] { EncounterTag.Scrolls }),
            new("SlimedBerserkerNormal", RoomType.Monster, false, Array.Empty<EncounterTag>()),
            new("SoulNexusElite", RoomType.Elite, false, Array.Empty<EncounterTag>()),
            new("TestSubjectBoss", RoomType.Boss, false, Array.Empty<EncounterTag>()),
            new("TheLostAndForgottenNormal", RoomType.Monster, false, Array.Empty<EncounterTag>()),
            new("TurretOperatorWeak", RoomType.Monster, true, Array.Empty<EncounterTag>()),
        },
        Events: new[] { "BattlewornDummy", "GraveOfTheForgotten", "HungryForMushrooms", "Reflections", "RoundTeaParty", "Trial", "TinkerTime" },
        Ancients: new[] { "Nonupeipe", "Tanx", "Vakuu" },
        AncientEpochGates: new Dictionary<string, string> {  });

    public static readonly ActDefinition[][] ByIndex =
    {
        new[] { Overgrowth, Underdocks },
        new[] { Hive },
        new[] { Glory },
    };

    public static readonly ActDefinition[] All = { Overgrowth, Underdocks, Hive, Glory };
}
