// <auto-generated>
//   The ordered contents of every relic pool, with rarities and epoch gates.
//   Read from Slay the Spire v0.109.1 by `sts2seed --refresh`, which asks the
//   game's own model database rather than parsing its source. Do not hand-edit:
//   order is load-bearing, and the next refresh will overwrite you.
//
//   COUNT Shared = 118
//   COUNT Ironclad = 8
//   COUNT Silent = 8
//   COUNT Defect = 8
//   COUNT Regent = 8
//   COUNT Necrobinder = 8
//   COUNT EpochGates = 15
// </auto-generated>

#nullable enable

namespace Sts2.SeedFinder.Core.Acts;

public enum Character { Ironclad, Silent, Defect, Regent, Necrobinder }

/// <summary>One relic as it sits in a pool, with the grab-bag rarity that buckets it.</summary>
public readonly record struct PoolRelic(string Name, string Slug, string Rarity);

public static class RelicPoolData
{
    /// <summary>Rarities a PLAYER's grab bag keeps, per RelicGrabBag._rarities. The shared
    /// bag is populated through the overload that skips this filter, so it holds every rarity.</summary>
    public static readonly string[] GrabBagRarities = { "Common", "Uncommon", "Rare", "Shop" };

    // Shared: 118 relics -> Ancient=2, Common=25, Event=1, Rare=35, Shop=25, Uncommon=30
    public static readonly PoolRelic[] SharedRelics =
    {
        new("Akabeko", "akabeko", "Uncommon"),
        new("AmethystAubergine", "amethyst_aubergine", "Common"),
        new("Anchor", "anchor", "Common"),
        new("ArtOfWar", "art_of_war", "Rare"),
        new("BagOfMarbles", "bag_of_marbles", "Common"),
        new("BagOfPreparation", "bag_of_preparation", "Common"),
        new("BeatingRemnant", "beating_remnant", "Rare"),
        new("Bellows", "bellows", "Rare"),
        new("BeltBuckle", "belt_buckle", "Shop"),
        new("BloodVial", "blood_vial", "Common"),
        new("BookOfFiveRings", "book_of_five_rings", "Common"),
        new("BowlerHat", "bowler_hat", "Uncommon"),
        new("Bread", "bread", "Shop"),
        new("BronzeScales", "bronze_scales", "Common"),
        new("BurningSticks", "burning_sticks", "Shop"),
        new("Candelabra", "candelabra", "Uncommon"),
        new("CaptainsWheel", "captains_wheel", "Rare"),
        new("Cauldron", "cauldron", "Shop"),
        new("CentennialPuzzle", "centennial_puzzle", "Common"),
        new("Chandelier", "chandelier", "Rare"),
        new("ChemicalX", "chemical_x", "Shop"),
        new("CloakClasp", "cloak_clasp", "Rare"),
        new("DingyRug", "dingy_rug", "Shop"),
        new("DollysMirror", "dollys_mirror", "Shop"),
        new("DragonFruit", "dragon_fruit", "Shop"),
        new("EternalFeather", "eternal_feather", "Uncommon"),
        new("FestivePopper", "festive_popper", "Common"),
        new("FresnelLens", "fresnel_lens", "Event"),
        new("FrozenEgg", "frozen_egg", "Rare"),
        new("GamblingChip", "gambling_chip", "Rare"),
        new("GamePiece", "game_piece", "Rare"),
        new("GhostSeed", "ghost_seed", "Shop"),
        new("Girya", "girya", "Rare"),
        new("GnarledHammer", "gnarled_hammer", "Shop"),
        new("Gorget", "gorget", "Common"),
        new("GremlinHorn", "gremlin_horn", "Uncommon"),
        new("HappyFlower", "happy_flower", "Common"),
        new("HornCleat", "horn_cleat", "Uncommon"),
        new("IceCream", "ice_cream", "Rare"),
        new("IntimidatingHelmet", "intimidating_helmet", "Rare"),
        new("JossPaper", "joss_paper", "Uncommon"),
        new("JuzuBracelet", "juzu_bracelet", "Common"),
        new("Kifuda", "kifuda", "Shop"),
        new("Kunai", "kunai", "Rare"),
        new("Kusarigama", "kusarigama", "Uncommon"),
        new("Lantern", "lantern", "Common"),
        new("LastingCandy", "lasting_candy", "Uncommon"),
        new("LavaLamp", "lava_lamp", "Shop"),
        new("LeesWaffle", "lees_waffle", "Shop"),
        new("LetterOpener", "letter_opener", "Uncommon"),
        new("LizardTail", "lizard_tail", "Rare"),
        new("LoomingFruit", "looming_fruit", "Ancient"),
        new("LuckyFysh", "lucky_fysh", "Uncommon"),
        new("Mango", "mango", "Rare"),
        new("MealTicket", "meal_ticket", "Common"),
        new("MeatOnTheBone", "meat_on_the_bone", "Rare"),
        new("MembershipCard", "membership_card", "Shop"),
        new("MercuryHourglass", "mercury_hourglass", "Uncommon"),
        new("MiniatureCannon", "miniature_cannon", "Uncommon"),
        new("MiniatureTent", "miniature_tent", "Shop"),
        new("MoltenEgg", "molten_egg", "Rare"),
        new("MummifiedHand", "mummified_hand", "Rare"),
        new("MysticLighter", "mystic_lighter", "Shop"),
        new("Nunchaku", "nunchaku", "Uncommon"),
        new("OddlySmoothStone", "oddly_smooth_stone", "Common"),
        new("OldCoin", "old_coin", "Rare"),
        new("Orichalcum", "orichalcum", "Uncommon"),
        new("OrnamentalFan", "ornamental_fan", "Uncommon"),
        new("Orrery", "orrery", "Shop"),
        new("Pantograph", "pantograph", "Uncommon"),
        new("ParryingShield", "parrying_shield", "Uncommon"),
        new("Pear", "pear", "Uncommon"),
        new("PenNib", "pen_nib", "Uncommon"),
        new("Pendulum", "pendulum", "Common"),
        new("Permafrost", "permafrost", "Uncommon"),
        new("PetrifiedToad", "petrified_toad", "Uncommon"),
        new("Planisphere", "planisphere", "Uncommon"),
        new("Pocketwatch", "pocketwatch", "Rare"),
        new("PotionBelt", "potion_belt", "Common"),
        new("PrayerWheel", "prayer_wheel", "Rare"),
        new("PunchDagger", "punch_dagger", "Shop"),
        new("RainbowRing", "rainbow_ring", "Rare"),
        new("RazorTooth", "razor_tooth", "Rare"),
        new("RedMask", "red_mask", "Common"),
        new("RegalPillow", "regal_pillow", "Common"),
        new("ReptileTrinket", "reptile_trinket", "Uncommon"),
        new("RingingTriangle", "ringing_triangle", "Shop"),
        new("RippleBasin", "ripple_basin", "Uncommon"),
        new("RoyalStamp", "royal_stamp", "Shop"),
        new("ScreamingFlagon", "screaming_flagon", "Shop"),
        new("Shovel", "shovel", "Rare"),
        new("Shuriken", "shuriken", "Rare"),
        new("SlingOfCourage", "sling_of_courage", "Shop"),
        new("SparklingRouge", "sparkling_rouge", "Uncommon"),
        new("StoneCalendar", "stone_calendar", "Rare"),
        new("StoneCracker", "stone_cracker", "Uncommon"),
        new("Strawberry", "strawberry", "Common"),
        new("StrikeDummy", "strike_dummy", "Common"),
        new("SturdyClamp", "sturdy_clamp", "Rare"),
        new("TheAbacus", "the_abacus", "Shop"),
        new("TheCourier", "the_courier", "Rare"),
        new("TinyMailbox", "tiny_mailbox", "Uncommon"),
        new("Toolbox", "toolbox", "Shop"),
        new("ToxicEgg", "toxic_egg", "Rare"),
        new("TungstenRod", "tungsten_rod", "Rare"),
        new("TuningFork", "tuning_fork", "Uncommon"),
        new("UnceasingTop", "unceasing_top", "Rare"),
        new("UnsettlingLamp", "unsettling_lamp", "Rare"),
        new("Vajra", "vajra", "Common"),
        new("Vambrace", "vambrace", "Uncommon"),
        new("VenerableTeaSet", "venerable_tea_set", "Common"),
        new("VeryHotCocoa", "very_hot_cocoa", "Ancient"),
        new("VexingPuzzlebox", "vexing_puzzlebox", "Rare"),
        new("WarPaint", "war_paint", "Common"),
        new("Whetstone", "whetstone", "Common"),
        new("WhiteBeastStatue", "white_beast_statue", "Rare"),
        new("WhiteStar", "white_star", "Rare"),
        new("WingCharm", "wing_charm", "Shop"),
    };

    // Ironclad: 8 relics -> Common=1, Rare=3, Shop=1, Starter=1, Uncommon=2
    public static readonly PoolRelic[] IroncladRelics =
    {
        new("Brimstone", "brimstone", "Shop"),
        new("BurningBlood", "burning_blood", "Starter"),
        new("CharonsAshes", "charons_ashes", "Rare"),
        new("DemonTongue", "demon_tongue", "Rare"),
        new("PaperPhrog", "paper_phrog", "Uncommon"),
        new("RedSkull", "red_skull", "Common"),
        new("RuinedHelmet", "ruined_helmet", "Rare"),
        new("SelfFormingClay", "self_forming_clay", "Uncommon"),
    };

    // Silent: 8 relics -> Common=1, Rare=3, Shop=1, Starter=1, Uncommon=2
    public static readonly PoolRelic[] SilentRelics =
    {
        new("HelicalDart", "helical_dart", "Rare"),
        new("NinjaScroll", "ninja_scroll", "Shop"),
        new("PaperKrane", "paper_krane", "Rare"),
        new("RingOfTheSnake", "ring_of_the_snake", "Starter"),
        new("SneckoSkull", "snecko_skull", "Common"),
        new("Tingsha", "tingsha", "Uncommon"),
        new("ToughBandages", "tough_bandages", "Rare"),
        new("TwistedFunnel", "twisted_funnel", "Uncommon"),
    };

    // Defect: 8 relics -> Common=1, Rare=3, Shop=1, Starter=1, Uncommon=2
    public static readonly PoolRelic[] DefectRelics =
    {
        new("CrackedCore", "cracked_core", "Starter"),
        new("DataDisk", "data_disk", "Common"),
        new("EmotionChip", "emotion_chip", "Rare"),
        new("GoldPlatedCables", "gold_plated_cables", "Uncommon"),
        new("PowerCell", "power_cell", "Rare"),
        new("Metronome", "metronome", "Rare"),
        new("RunicCapacitor", "runic_capacitor", "Shop"),
        new("SymbioticVirus", "symbiotic_virus", "Uncommon"),
    };

    // Regent: 8 relics -> Common=1, Rare=3, Shop=1, Starter=1, Uncommon=2
    public static readonly PoolRelic[] RegentRelics =
    {
        new("DivineRight", "divine_right", "Starter"),
        new("FencingManual", "fencing_manual", "Common"),
        new("GalacticDust", "galactic_dust", "Uncommon"),
        new("LunarPastry", "lunar_pastry", "Rare"),
        new("MiniRegent", "mini_regent", "Rare"),
        new("OrangeDough", "orange_dough", "Rare"),
        new("Regalite", "regalite", "Uncommon"),
        new("VitruvianMinion", "vitruvian_minion", "Shop"),
    };

    // Necrobinder: 8 relics -> Common=1, Rare=3, Shop=1, Starter=1, Uncommon=2
    public static readonly PoolRelic[] NecrobinderRelics =
    {
        new("BigHat", "big_hat", "Rare"),
        new("BoneFlute", "bone_flute", "Common"),
        new("BookRepairKnife", "book_repair_knife", "Uncommon"),
        new("Bookmark", "bookmark", "Rare"),
        new("BoundPhylactery", "bound_phylactery", "Starter"),
        new("FuneraryMask", "funerary_mask", "Uncommon"),
        new("IvoryTile", "ivory_tile", "Rare"),
        new("UndyingSigil", "undying_sigil", "Shop"),
    };

    /// <summary>Relics dropped from a pool when the named epoch is NOT revealed, by pool.
    /// Removal preserves the surviving order, which is what the deques are built from.</summary>
    public static readonly IReadOnlyDictionary<string, IReadOnlyDictionary<string, string[]>> EpochGates =
        new Dictionary<string, IReadOnlyDictionary<string, string[]>>
        {
            ["Shared"] = new Dictionary<string, string[]>
            {
                ["Relic1Epoch"] = new[] { "IntimidatingHelmet", "ReptileTrinket", "UnsettlingLamp" },
                ["Relic2Epoch"] = new[] { "BookOfFiveRings", "IceCream", "Kusarigama" },
                ["Relic3Epoch"] = new[] { "FestivePopper", "RippleBasin", "VexingPuzzlebox" },
                ["Relic4Epoch"] = new[] { "MiniatureCannon", "TungstenRod", "WhiteStar" },
                ["Relic5Epoch"] = new[] { "BeatingRemnant", "JossPaper", "TinyMailbox" },
            },
            ["Ironclad"] = new Dictionary<string, string[]>
            {
                ["Ironclad3Epoch"] = new[] { "PaperPhrog", "RedSkull", "RuinedHelmet" },
                ["Ironclad6Epoch"] = new[] { "CharonsAshes", "DemonTongue", "SelfFormingClay" },
            },
            ["Silent"] = new Dictionary<string, string[]>
            {
                ["Silent3Epoch"] = new[] { "PaperKrane", "Tingsha", "ToughBandages" },
                ["Silent6Epoch"] = new[] { "HelicalDart", "SneckoSkull", "TwistedFunnel" },
            },
            ["Defect"] = new Dictionary<string, string[]>
            {
                ["Defect3Epoch"] = new[] { "DataDisk", "Metronome", "SymbioticVirus" },
                ["Defect6Epoch"] = new[] { "EmotionChip", "GoldPlatedCables", "PowerCell" },
            },
            ["Regent"] = new Dictionary<string, string[]>
            {
                ["Regent3Epoch"] = new[] { "FencingManual", "GalacticDust", "LunarPastry" },
                ["Regent6Epoch"] = new[] { "MiniRegent", "OrangeDough", "Regalite" },
            },
            ["Necrobinder"] = new Dictionary<string, string[]>
            {
                ["Necrobinder3Epoch"] = new[] { "BoneFlute", "BookRepairKnife", "FuneraryMask" },
                ["Necrobinder6Epoch"] = new[] { "BigHat", "Bookmark", "IvoryTile" },
            },
        };

    public static PoolRelic[] RelicsFor(Character c) => c switch
    {
        Character.Ironclad => IroncladRelics,
        Character.Silent => SilentRelics,
        Character.Defect => DefectRelics,
        Character.Regent => RegentRelics,
        Character.Necrobinder => NecrobinderRelics,
        _ => IroncladRelics,
    };

    /// <summary>The pool key EpochGates uses for a character.</summary>
    public static string PoolKey(Character c) => c.ToString();
}
